import test,{chromium, expect} from '@playwright/test'
test('createIndividuals',async({page})=>{
    await page.goto("https://login.salesforce.com/?locale=in")
    await page.locator('#username').fill('vidyar@testleaf.com')
    await page.locator('#password').fill('Sales@123')
    await page.locator("[name='Login']").click()
    await page.locator("//div[@class='slds-r5']").click()
    await page.locator("//button[@aria-label='View All Applications']").click()
    await page.getByPlaceholder("Search apps or items...").fill('individuals')
    await page.waitForTimeout(5000)
    await page.locator(`text='Individuals'`).click()
    await page.locator(`text='Midun'`).click()
    await page.locator("//div[@title='Edit']").click()
    await page.locator("(//a[@class='select'])[1]").click()
    await page.locator("//a[@title='Mrs.']").click()
    await page.getByPlaceholder("First Name").fill('Neethu')
    await page.locator(`text='Save'`).click()
    const firstName=await page.textContent(`text='Midun'`)
    expect(firstName).toContain('Midun')
})