import test,{expect,chromium} from '@playwright/test'
test('createNewAccount',async({page})=>{
await page.goto('https://login.salesforce.com/?locale=in')
await page.getByLabel("Username").fill('vidyar@testleaf.com')
await page.getByLabel("Password").fill('Sales@123')
await page.locator('#Login').click()
await page.waitForTimeout(5000)
await expect(page).toHaveTitle("Home | Salesforce")
await expect(page).toHaveURL("https://testleaf-da-dev-ed.develop.lightning.force.com/lightning/setup/SetupOneHome/home")
await page.waitForTimeout(5000)
await page.locator('.slds-r4').click()
await page.locator(`'View All'`).click()
await page.getByPlaceholder("Search apps or items...").fill('Service')
await page.locator("(//div[@class='slds-truncate'])[2]").click()
await page.locator("//span[text()='Accounts']").click()
await page.locator("//div[@title='New']").click()
await page.locator("[name='Name']").fill('Neethu Vairamani')
await page.locator("//button[@class='slds-button slds-button_brand']").click()
await page.waitForTimeout(5000)
await expect(page.getByText('Account "Neethu Vairamani" was created.')).toBeVisible()
await page.waitForTimeout(5000)
})
