import test, {chromium} from'@playwright/test'
test('create a Lead',async({page})=>{
    await page.goto('http://leaftaps.com/opentaps/control/main')    
    await page.locator('#username').fill('Demosalesmanager')    
    await page.locator('#password').fill('crmsfa')    
    await page.locator('.decorativeSubmit').click()
    await page.locator(`text='CRM/SFA'`).click()   
    await page.locator(`text='Leads'`).click()   
    await page.getByRole('link',{name:'Create Lead'}).click()
    await page.locator('#createLeadForm_companyName').fill('INFOSYS')    
    await page.locator('#createLeadForm_firstName').fill('Neethu')   
    await page.locator('#createLeadForm_lastName').fill('Vairamani')   
    await page.locator('[name=personalTitle]').fill('Mrs')
    await page.locator("//input[@name='generalProfTitle']").fill('Tester')
    await page.locator('#createLeadForm_annualRevenue').fill('500000')
    await page.locator('[name=departmentName]').fill('Playwright')
    await page.locator('#createLeadForm_primaryPhoneNumber').fill('938410678')
    await page.locator("//input[@value='Create Lead']").click()
    await page.waitForTimeout(6000)
    const title= await page.title()
    console.log(title)
})