import test , {expect,chromium} from '@playwright/test'

test('Edit A Lead',async({page})=>{
    await page.goto('http://leaftaps.com/opentaps/control/main')
    await page.locator('#username').fill('Demosalesmanager')    
    await page.locator('#password').fill('crmsfa')    
    await page.locator('.decorativeSubmit').click()
    await page.locator(`text='CRM/SFA'`).click()   
    await page.locator(`text='Leads'`).click()   
    await page.getByRole("link",{name:'Find Leads'}).click()
    await page.locator("(//input[@name='firstName'])[3]").fill('Neethu')
    await page.waitForTimeout(6000)
    await page.getByRole("button",{name:'Find Leads'}).click()
    await page.waitForTimeout(6000)
    await page.locator(`text='14745'`).click()
    await page.waitForTimeout(6000)
    await page.locator(`text='Edit'`).click()
    await page.locator('#updateLeadForm_companyName').fill('INFOSYS PVT LIMITED')
    await page.locator('#updateLeadForm_annualRevenue').fill('600000')
    await page.locator('#updateLeadForm_departmentName').fill('Automation PW')
    await page.locator('#updateLeadForm_description').fill('Learning PW Concept')
    await page.locator("//input[@value='Update']").click()
    const companyName= await page.textContent('#viewLead_companyName_sp')
    expect(companyName).toContain('INFOSYS PVT LIMITED')
    const annualRevenue= await page.textContent('#viewLead_annualRevenue_sp')
    expect(annualRevenue).toContain('$600,000.00')
    const departmentName= await page.textContent('#viewLead_departmentName_sp')
    expect(departmentName).toContain('Automation PW')
    const description= await page.textContent('#viewLead_description_sp')
    expect(description).toContain('Learning PW Concept')

    const title= await page .title()
    console.log(title)
})

